R/tables.r
When there are many tables in the dataset, I cannot retrieve a full list of them without option max_results. But after I added this parameter, got this error:
```
> histTxnTables <- list_tables(bqdaproject, bqBaseDataset)
Auto-refreshing stale OAuth token.
> histTxnTables <- list_tables(bqdaproject, bqBaseDataset, 1000)
Error: HTTP error [404] Not Found
```
=> Cannot use max_results in function list_tables()

NEWS.md, R/request.r, tests/testthat/test-request.r
This adds support for API keys to bigrquery, reading them from the
`BIGRQUERY_API_KEY` environment variable. They're used in all API calls when
present.
PTAL @hadley
=> Add support for reading API keys from an env var.

R/request.r
This improves robustness by checking the HTTP status code instead of relying on the status text, related to hadley/httr#305.
=> use status_code for success determination

R/zzz.r
to support is_quiet() when loading package without attaching
Should the option be renamed to `bigrquery.quiet` (now: `bigquery.quiet`)?
=> set default options in .onLoad() instead of .onAttach()

R/auth.r
This adds internal support for the service account for use with BigQuery.
```
bigrquery:::set_service_token("/path/to/token.json")
bigrquery::list_projects()
```
=> internal service token support

R/tabledata.r
There was a floating unused `callback` argument in `list_tabledata_iter()` that was causing my queries to throw an error.
=> Removed unused argument.

NEWS.md, R/tables.r, R/upload.r, man/copy_table.Rd, man/insert_upload_job.Rd
analogously to copy_table(), except for the default value for `write_disposition` which is `"WRITE_APPEND"` instead of `"WRITE_EMPTY"`.
Closes #33.
=> insert_upload_job() gains create_disposition and write_disposition args

R/dplyr.r
This pull request adds `ifelse` function SQL translation.
Google BigQuery has a direct equivalent to R's `ifelse` function which is called `IF`.  
According to [reference](https://cloud.google.com/bigquery/query-reference#otherfunctions), the function is in a category called "Other functions" and accepts 3 arguments just like `ifelse` does.
An example test case is listed below
``` r
library(dplyr)
library(bigrquery)
BILLING_PROJECT <- "<YOUR_BILLING_PROJECT>"
BILLING_DATASET <- "<DATASET_INSIDE_THAT_PROJECT>"
bq <- src_bigquery(BILLING_PROJECT, BILLING_DATASET)
df <- data.frame(a = 1:100, b = 101:200)
ifelse_test_df <- copy_to(bq, df, name = "ifelse_test_df")
ifelse_test_df %>%
mutate( z = ifelse(a <= 10L, 1L, 0L) ) %>%
summarise( sum_z = sum(z) ) %>%
collect
```
The use of function with …
=> Added ifelse -> IF() function mapping

DESCRIPTION, R/jobs.r, R/query.r, man/insert_query_job.Rd, man/query_exec.Rd
As mentioned in issue #117, Google recently added support for executing queries written in [standard SQL](https://cloud.google.com/bigquery/sql-reference/) (in addition to legacy SQL). To use it in BigRQuery I just added an argument `useLegacySql` to a few functions and included the value in the REST call.
Thanks for a great package and hope you find this update useful!
=> Added support for sending the useLegacySql parameter in REST calls.

R/dplyr.r
Use `LOGICAL_AND()` instead of nonexistent `LOGICAL_ANY()`. Fixing #174.
=> Fix all() SQL translation

NEWS.md, R/dplyr.R
`median()` function translates to `APPROX_QUANTILES(x, 2)[SAFE_ORDINAL(2)]`. This fix was suggested by @edgararuiz (https://github.com/r-dbi/bigrquery/issues/267#issuecomment-423320332), but apparently not implemented.
=> add translation for `median()` function

R/bq-table.R
Example introduced in #296 referenced the wrong function
=> Fixing example with wrong function

cran-comments.md, src/BqField.cpp
According to `` check_on_solaris(env_vars = c(`_R_CHECK_FORCE_SUGGESTS_` = "false")) ``, this fixes things on Solaris (i.e. we get a successful installation and clean `R CMD check`).
bigrquery currently fails to install on Solaris:
https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/bigrquery-00check.html
=> Fixes installation failure on Solaris

NEWS.md, R/bq-download.R
I don't see any particular reason to keep the files after they have been parsed. What do you think?
In reference to https://github.com/r-dbi/bigrquery/issues/343
=> Clean tmp files after bq_table_download

NEWS.md, R/bq-download.R, tests/testthat/test-bq-download.R
Fixes #395.
I work on the All of Us Researcher Workbench project (https://github.com/all-of-us/workbench) where we guide users to fetch data from BigQuery via the bigrquery package. The issue above has been affecting our users, so we wanted to take a swing at a fix.
**Rationale**
This is a fix with more limited scope than the `httpr` alternative (https://github.com/r-lib/httr/pull/670). We simply force the page params 
**Testing**
- devtools::check() runs successfully.
- I confirmed that the added regression test fails if the code change is commented out.
- Open to suggestions for an alternative test strategy. This approach (using opts to force aggressive scientific formatting) is a bit more clever than I'd like, but it prevents us from needing to load ~100k rows to trigger this scenario. …
=> Force BQ page query params to not use scientific notation

R/bq-dataset.R, R/bq-download.R, R/bq-job.R, R/bq-perform.R, R/bq-project.R, R/bq-projects.R, R/bq-table.R, man/api-dataset.Rd, man/api-job.Rd, man/api-perform.Rd, man/api-project.Rd, man/api-table.Rd, man/bq_projects.Rd, man/bq_table_download.Rd
* added "Google BigQuery" ahead of "API Documentation"
* `bq-table.R`: minor formatting fix in help
=> documentation edits

DESCRIPTION, R/bq-auth.R, R/zzz.R
Creating the .auth object directly at the top-level means the code
from gargle is snapshotted at build time.
This is needed for r-lib/gargle#157, but is a good change even without that PR.
=> Don't init .auth object until .onLoad

NEWS.md, R/dbi-result.R
To facilitate integration of dbFetch with bigrquerystorage package.
BigQueryReadClient requires a billing project to iniate a ReadSession.
=> Add `billing` slot to `BigQueryResult`

NEWS.md, R/dplyr.R
Fixes #439 - dplyr snytax with `collect()` now returns bit64::integer64 values as expected when reading BigQuery table with int64 column:
```{r}
...
tbl(con, long_table_name ) %>%
select(int64_identifier) %>%
collect() %>%
glimpse()
#> Rows: 32
#> Columns: 1
#> $ int64_identifier <int64> 9223372036854775800, 9223372036854775800, 922337203…
```
PR passes `devtools::check()`
=> collect now passes con bigint parameter to bq_table_download

NEWS.md
After submission, caught that #440 also solves #437 (when `tbl()` is evaluated without explicitly calling `collect()`) 
I wanted to rewrite my news item to slightly clarify my language and also reference that issue. Thanks!
=> rewrite news item for #440 to reference #437

src/RcppExports.cpp
This appears with Rcpp 1.0.7.
Mostly doing this to keep it out of my PR re: table download pagination.
=> Re-build with current Rcpp

DESCRIPTION, NEWS.md, R/bq-download.R
I have my own package that I'm working on, and it happens to include a `R CMD CHECK` test that calls a `bigrquery` function.
This test has been failing because `bigrquery` has `readr` in the Suggests section of the DESCRIPTION rather than the Imports. Fortunately this is a quick fix.
Here is an example of where `readr` is used in `bigrquery`:
https://github.com/r-dbi/bigrquery/blob/main/R/bq-download.R#L340
=> Add readr to Imports

tests/testthat/bq-job-errors.txt, tests/testthat/test-bq-job.R, tests/testthat/test-dplyr.R
There were 3 issues:
1. The warning about the old dbplyr interface. I simply wrapped this in `expect_warning()` as I won't migrate bigrquery to dbplyr edition 2 (as I'm not using bigquery at all...).
2. The expected errros in `bq-job-errors.txt`. One changed slightly due to rlang. The other does not error anymore. Probably bigquery does not throw an error anymore. I added a note that this should be updated but this should be someone more experienced with bigquery.
3. The last error seems to be random. `bq_test_dataset()` is successfully called  a couple of times before and I cannot reproduce it either.
=> dbplyr compat part 2

NEWS.md, R/bq-request.R, R/gs-object.R
Align Google APIs URLs with Discovery docs per #541 
* Align Google APIs URLs to Google Cloud Discovery docs. This enables support for Private and Restricted Google APIs configurations.
- `R/bq-request.R`
- Substitute `https://bigquery.googleapis.com` for `https://www.googleapis.com`
- `R/gs-object.R`
- Substitute `https://storage.googleapis.com` for `https://www.googleapis.com`
- No updates to OAuth scope URLs 
- (E.G. `https://www.googleapis.com/auth...`). These do not require change.
* Update NEWS.md and bump version to 1.4.3
=> Align Google APIs URLs with Discovery docs per #541 

NEWS.md, R/bq-test.R, R/dbi-result.R, R/utils.R, tests/testthat/_snaps/bq-download.md, tests/testthat/_snaps/dbi-result.md, tests/testthat/test-dbi-result.R
And default to verbose output when snapshotting.
Fixes #463
=> dbFetch() respects the quiet parameter

DESCRIPTION
The [use of `gargle::secret_has_key()`](https://github.com/r-dbi/bigrquery/blob/42dd4d2969600071ad7ccb8b11b052a2daae5d52/R/bq-auth.R#L101-L103) entails `gargle >=1.5.0` (see [v1.4.0...v1.5.0 diff](https://github.com/r-lib/gargle/compare/v1.4.0...v1.5.0#diff-b6b6854a02ae177f8860f49654ff250c1554d021ae434b6efdbe99d00bdc6055)). This PR updates DESCRIPTION to reflect that.
=> Raise minimum `gargle` version to 1.5

R/dplyr.R, man/src_bigquery.Rd, tests/testthat/test-dplyr.R
This pull request updates the example in the `dplyr.R` and `src_bigquery.Rd` files to highlight the use of the `I()` function for nested table identifiers.
It also adds unit tests for nested table identifier.
https://www.tidyverse.org/blog/2024/04/dbplyr-2-5-0/
Resolves #605
=> docs: Update example to highlight I() for nested table identifier

DESCRIPTION, R/bq-perform.R
Hi @hadley,
This pull request aims to eliminate disk writing when PARQUET is selected as the transmission format by the user.
Thanks @gaborcsardi  for the new nanoparquet feature
Regards,
=> Write Parquet file into a memory buffer

R/bq-perform.R
Hi @hadley,
This pull request aims to address the error encountered in the live API. This error occurs because when source_format is not defined, a vector of length 2 is being passed to unbox. Therefore, the correction for this error involves updating the source_format variable when arg_match is performed.
Regards,
=> Fix bq_table_upload when source_format is undefined

tests/testthat/test-dplyr.R
`sql_runif()` was only added in 2.4.0:
https://github.com/tidyverse/dbplyr/blob/860bd6adf988a2b039485030d234eba05ee46a3c/NEWS.md?plain=1#L199
=> Skip test requiring recent dbplyr

DESCRIPTION
Hi @hadley,
This pull request aims to update the nanoparquet version to 0.3.0 since it is now available on CRAN.
Regards,
=> Update the required version of nanoparquet

R/bq-perform.R, man/api-perform.Rd
Hi @hadley,
This pull request aims to update the documentation of the ` bq_perfom_extract ` function, as the BigQuery documentation (https://cloud.google.com/bigquery/docs/exporting-data) specifies that the Parquet format is supported. However, this format is not listed as supported in the documentation of this library.
Regards,
=> Update bq_perform_extract documentation

DESCRIPTION
Hi @hadley,
This pull request aims to update the nanoparquet version to >0.3.1 since a bug has been identified https://github.com/r-lib/nanoparquet/issues/77 which has already been fixed.
Regards,
=> Update the required version of nanoparquet (>3.0.1)
