r-dbi/bigrquery

R/bigrquery.r
README.md
man/bigrquery.Rd

Following the move, updates occurrences of `hadley/bigrquery` to `rstats-db/bigrquery`.

rename to rstats-db

---

R/query.r

to allow consumption of results using list_tabledata_iter()

Extract run_query_job()

---

NEWS.md
R/jobs.r
R/tabledata.r
R/zzz.r
man/list_tabledata.Rd
man/wait_for.Rd

https://github.com/rstats-db/bigrquery/pull/76#issuecomment-171723085

Rename option bigquery.quiet to bigrquery.quiet

---

R/tabledata.r

detected using RStudio's shortcut Ctrl+Alt+Shift+P. Marvelous!

Use normal assignment for initialization

---

.travis.yml

Use native R testing

---

R/dplyr.r
tests/testthat/test-sql.R

Fix %||% function's SQL translation

---

R/dplyr.r

Fix window function translations

---

R/dplyr.r

Fix pmin() and pmax() SQL translation

---

README.md

Brings to the front how to connect and use Big Query using `DBI` and `dplyr`

Adds DBI/dplyr refs to Readme

---

.travis.yml

I see this syntax in many other `.travis.yml`'s.
Fixes #216

Another attempt to skip token decryption for PRs

---

R/bq-table.R
man/api-table.Rd
tests/testthat/test-bq-table.R

Updated examples and test to demonstrate how table metadata can be added

---

README.Rmd
README.md

Fix header level

---

NEWS.md
R/dplyr.R

This is my first pull request, I hope it's done right.

Changed str_detect per issue #369.

---

.github/workflows/live-api.yml

Part of #529 
All the other workflows appear to be up-to-date, but this one had not been touched in a long while.

Update live api workflow

---

NEWS.md
R/dplyr.R
tests/testthat/test-dplyr.R

Ensure op_can_download() returns FALSE for hand rolled sql

---

NEWS.md
R/dbi-connection.R
R/dplyr.R
tests/testthat/_snaps/dbi-connection.md
tests/testthat/_snaps/dplyr.md
tests/testthat/test-dbi-connection.R
tests/testthat/test-dplyr.R

Hack in dbplyr 2.4.0 support

---

DESCRIPTION
NEWS.md
R/dplyr.R
R/import-standalone-s3-register.R
R/zzz.R
tests/testthat/test-dplyr.R

Update to dbplyr interface 2e

---

DESCRIPTION
R/bq-download.R
R/bq-perform.R
R/utils.R
tests/testthat/test-bq-dataset.R
tests/testthat/test-bq-table.R
tests/testthat/test-dplyr.R

Use own defer implementation

---

NEWS.md
R/dbi-connection.R
man/DBI.Rd
tests/testthat/test-dbi-connection.R

Support DBI::Id()

---

NEWS.md
R/dbi-connection.R

Use connection billing in dbWriteTable()

---

NEWS.md
R/dbi-connection.R
tests/testthat/test-dbi-connection.R

Implement a dbCreateTable method

---

R/bq-download.R

I guess they might not be created in the case of error? Fixes #521

Delete files silently

---

NEWS.md
R/dplyr.R
tests/testthat/test-dplyr.R

Improve median translations

---

README.Rmd
README.md

Make it clearer how to get started with an account

---

NEWS.md
R/dplyr.R
R/zzz.R
tests/testthat/test-dplyr.R

Implement same_src

---

NEWS.md
R/dplyr.R
R/zzz.R
tests/testthat/test-bq-job.R
tests/testthat/test-dplyr.R

Add support for views

---

R/bq-field.R
man/bq_field.Rd

Improve `bq_field()` docs

---

NEWS.md
R/dplyr.R
tests/testthat/test-dplyr.R

Which appear to error when you attempt to get their metadata. Fixes #468

Support views in the INFORMATION_SCHEMA schema

---

R/bq-download.R
tests/testthat/test-bq-download.R

Parse fractional seconds

---

R/dplyr.R
tests/testthat/test-dplyr.R

Fully specify generated table name

---

R/connections-page.R
R/dbi-connection.R
tests/testthat/test-bq-dataset.R

* Provide (undocumented) hint argument
* Drop one level of nesting
* Use dataset if set in connection

Connection pane improvements
